<?php require "template/header.phtml"; ?>

<h1>Crear Curso</h1>
<form action="added-course" method="POST">
  <div class="form-group">
    <label for="title">Título:</label>
    <input type="text" class="form-control" id="title" name="title" maxlength="100" required>
  </div>
  <div class="form-group">
    <label for="category">Categoría:</label>
    <select class="form-control" id="category" name="category" required>
      <?php foreach($categories as $category): ?>
        <option value=""><?= $category->category_name ?> </option>
      <?php endforeach ?>
    </select>
  </div>
  <div class="form-group">
    <label for="description">Descripción:</label>
    <textarea class="form-control" id="description" name="description" rows="4" required></textarea>
  </div>
  <div class="form-group">
    <label for="teacher">Profesor:</label>
    <select class="form-control" id="teacher_id" name="teacher_id" required>
      <?php foreach($teachers as $teacher): ?>
        <option value=""><?= $teacher->name ?> </option>
      <?php endforeach ?>
    </select>
  </div>
  <div class="form-group">
    <label for="link">Enlace:</label>
    <input type="text" class="form-control" id="link" name="link">
  </div>
  <button type="submit" class="btn btn-primary">Crear Curso</button>
</form>

