<?php require "template/header.phtml"; ?>
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900 color-p">Agregar Curso</h2>
  </div>
  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <form class="space-y-6" action="create-course" method="POST">
      <div class="form-group">
        <label class="block text-sm font-medium leading-6 text-gray-900 color-p" for="title">Título:</label>
        <input
          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
          type="text" id="title" name="title" maxlength="100" required>
      </div>
      <div class="form-group">
        <label class="block text-sm font-medium leading-6 text-gray-900 color-p" for="category">Categoría:</label>
        <select
          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
          id="category" name="category" required>
          <?php foreach ($categories as $category): ?>
            <option value="<?= htmlspecialchars($category->category_id, ENT_QUOTES, 'UTF-8') ?>">
              <?= htmlspecialchars($category->category_name, ENT_QUOTES, 'UTF-8') ?>
            </option>
          <?php endforeach; ?>
        </select>
      </div>
      <div class="form-group">
        <label class="block text-sm font-medium leading-6 text-gray-900 color-p" for="description">Descripción:</label>
        <textarea
          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
          id="description" name="description" rows="4" required></textarea>
      </div>
      <div class="form-group">
        <label class="block text-sm font-medium leading-6 text-gray-900 color-p" for="teacher">Profesor:</label>
        <select
          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
          id="teacher_id" name="teacher_id" required>
          <?php foreach ($teachers as $teacher): ?>
            <option value="<?= $teacher->teacher_id ?>">
              <?= $teacher->name ?>
            </option>
          <?php endforeach; ?>
        </select>
      </div>
      <div class="form-group">
        <label class="block text-sm font-medium leading-6 text-gray-900 color-p" for="link">Enlace:</label>
        <input
          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
          type="text" id="link" name="link">
      </div>
      <div class="form-group">
        <label class="block text-sm font-medium leading-6 text-gray-900 color-p" for="minutes">Duracion en
          minutos:</label>
        <input
          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
          type="text" class="form-control" id="minutes" name="minutes">
      </div>
      <button type="submit"
        class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 custom-button button-add">
        Crear Curso
      </button>
    </form>
  </div>
</div>
<?php require "template/footer.phtml"; ?>