<?php require './template/header.phtml' ?>

<div class="container px-6 py-10 mx-auto">
    <h1 class="color-p text-2xl font-semibold text-gray-800 capitalize lg:text-3xl dark:text-white">Cursos</h1>

    <div class="filter d-flex flex-column flex-md-row justify-content-between align-items-center">
        <div class="dropdown-center-left mb-3 mb-md-0">
            <button class="select-filter btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Filtrar por Categoria
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="courses">Todos</a></li>
                <?php foreach ($categories as $category): ?>
                    <li><a class="dropdown-item" href="courses-category/<?= $category->category_id ?>">
                            <?= $category->category_name ?>
                        </a></li>
                <?php endforeach ?>
            </ul>
        </div>

        <div class="dropdown-center-right">
            <button class="select-filter btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Filtrar por Profesor
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="courses">Todos</a></li>
                <?php foreach ($teachers as $teacher): ?>
                    <li><a class="dropdown-item" href="courses-teacher/<?= $teacher->teacher_id ?>">
                            <?= $teacher->name ?>
                        </a></li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>



    <div class="grid grid-cols-1 gap-8 mt-8 md:mt-16 md:grid-cols-2">

        <?php foreach ($courses as $course): ?>
            <div class="card mb-3 video-card">
                <iframe class="card-img-top" src="<?= $course->link ?>" frameborder="0" allowfullscreen></iframe>
                <div class="card-body">
                    <h5 class="card-title">
                        <a style="color: white;" href="course/<?= $course->course_id ?>"> <?= $course->title ?></a>
                    </h5>
                    <span
                        class="px-3 py-1 text-xs text-blue-800 uppercase bg-blue-200 rounded-full dark:bg-blue-300 dark:text-blue-900"> <?php
                        $categoryId = $course->category;
                        $categoryName = '';

                        // Suponiendo que $categories es un array de objetos donde cada objeto tiene 'category_id' y 'category_name'
                        foreach ($categories as $category) {
                            if ($category->category_id == $categoryId) {
                                $categoryName = $category->category_name;
                                break;
                            }
                        }

                        // Mostrar el nombre de la categoría
                        echo htmlspecialchars($categoryName);
                        ?></span>
                    <p class="card-text">
                        <?= $course->description ?>
                    </p>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</div>
<?php require './template/footer.phtml' ?>