<?php require './template/header.phtml' ?>

<div class="container px-6 py-10 mx-auto">
    <h1 class="color-p text-2xl font-semibold text-gray-800 capitalize lg:text-3xl dark:text-white">Cursos</h1>

    <div class="filter d-flex flex-column flex-md-row justify-content-between align-items-center">
        <div class="dropdown-center-left mb-3 mb-md-0">
            <button class="select-filter btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Filtrar por Categoria
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="">Todos</a></li>
                <?php foreach($categories as $category): ?>
                <li><a class="dropdown-item" href="courses-category/<?= $category->category_name ?>">
                        <?= $category->category_name ?>
                    </a></li>
                <?php endforeach ?>
            </ul>
        </div>

        <div class="dropdown-center-right">
            <button class="select-filter btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Filtrar por Profesor
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="">Todos</a></li>
                <?php foreach($teachers as $teacher): ?>
                <li><a class="dropdown-item" href="courses-teacher/<?= $teacher->teacher_id ?>">
                        <?= $teacher->name ?>
                    </a></li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>



    <div class="grid grid-cols-1 gap-8 mt-8 md:mt-16 md:grid-cols-2">

        <?php foreach($courses as $course): ?>
        <div class="card mb-3 video-card">
            <iframe class="card-img-top" src="<?= $course->link ?>" frameborder="0" allowfullscreen></iframe>
            <div class="card-body">
                <h5 class="card-title">
                    <?= $course->title ?>
                </h5>
                <p class="card-text">
                    <?= $course->description ?>
                </p>
            </div>
        </div>
        <?php endforeach ?>
    </div>
</div>
<?php require './template/footer.phtml' ?>