<?php require './template/header.phtml'; ?>
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">

        <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900 color-p">Editar Curso
        </h2>
    </div>
    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
        <?php if (!empty($teacher)): ?>
            <?php $teacher = $teacher[0]; ?>
            <?php if (is_object($teacher)): ?>
                <form class="space-y-6" action="update-teacher/<?= $teacher->teacher_id ?>" method="post">

                    <label class="block text-sm font-medium leading-6 text-gray-900 color-p" for="name">Nombre:</label>
                    <input
                        class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                        type="text" id="name" name="name" value="<?= $teacher->name ?>" required><br><br>

                    <label class="block text-sm font-medium leading-6 text-gray-900 color-p" for="profile_picture">URL de la
                        Foto de Perfil:</label>
                    <input
                        class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                        type="url" id="profile_picture" name="profile_picture" value="<?= $teacher->profile_picture ?>"
                        required><br><br>

                    <label class="block text-sm font-medium leading-6 text-gray-900 color-p"
                        for="description">Descripción:</label>
                    <textarea
                        class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                        id="description" name="description" required><?= $teacher->description ?></textarea><br><br>

                    <label class="block text-sm font-medium leading-6 text-gray-900 color-p" for="bio">Biografía:</label>
                    <textarea
                        class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                        id="bio" name="bio" required><?= $teacher->bio ?></textarea><br><br>

                    <button type="submit"
                        class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 custom-button button-add">Guardar
                        cambios
                    </button>
                </form>
            <?php else: ?>
                <p>Error: Profesor no encontrado.</p>
            <?php endif; ?>
        <?php else: ?>
            <p>Profesor no encontrado.</p>
        <?php endif; ?>

        <?php require './template/footer.phtml'; ?>