<!DOCTYPE html>
<html lang="en">

<!-- head -->

<head>
  <meta charset="UTF-8">
  <base href="<?= BASE_URL ?>">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="css/styles.css" type="text/css" />
  <title>Página de juegos</title>
</head>

<body>
  <!-- main header -->
  <header>



    <nav class="navbar navbar-expand-lg ">
      <div class="container-fluid">
        <a class="navbar-brand color-p" href="home">Cursos IT</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link color-p" href="courses">Cursos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link color-p" href="teachers">Profesores</a>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
              <?php if (AuthHelper::isLoggedin() && AuthHelper::isAdmin()): ?>
                <a class="nav-link color-p" href="home-admin">Admin</a>
              <?php endif ?>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
              <?php if (!AuthHelper::isLoggedin()): ?>
                <a class="nav-link color-p" href="login">Iniciar sesión</a>
              <?php else: ?>
                <a class="nav-link color-p" href="logout">Cerrar sesión (<?= $_SESSION['USER_USERNAME'] ?>)</a>
              <?php endif ?>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"></script>
  </header>

  <!-- inicio main container -->
  <main>