<?php require './template/header.phtml'; ?>

<div class="container px-6 py-16 mx-auto text-center">
        <div class="max-w-lg mx-auto">
            <h1 class="text-3xl font-semibold text-gray-800 dark:text-white lg:text-4xl color-p">Empeza tu carrera IT con cursos gratuitos de la comunidad</h1>
            <p class="mt-6 text-gray-500 dark:text-gray-300">Son cursos creados por personas de la industria y que en sus tiempos libres son influencers </p>
           <button class="custom-button px-5 py-2 mt-6 text-sm font-medium leading-5 text-center text-white capitalize rounded-lg lg:mx-0 lg:w-auto focus:outline-none">
                <a class="color-p" href="courses">Explora los cursos disponibles</a>
            </button>
              <button class="custom-button px-5 py-2 mt-6 text-sm font-medium leading-5 text-center text-white capitalize rounded-lg lg:mx-0 lg:w-auto focus:outline-none">
                <a class="color-p" href="teachers">Explora entre los profesores</a>
            </button>
        </div>

        <div class="flex justify-center mt-10">
            <img class="object-cover w-full h-96 rounded-xl lg:w-4/5" src="https://images.unsplash.com/photo-1556761175-5973dc0f32e7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1632&q=80" />
        </div>
    </div>

<?php require './template/footer.phtml'; ?>
