<?php require './template/header.phtml' ?>

<div class="w-full max-w-sm mx-auto overflow-hidden bg-white rounded-lg shadow-md dark:bg-gray-800 mt-20">
    <div class="px-6 py-4">

        <h3 class="mt-3 text-xl font-medium text-center text-gray-600 dark:text-gray-200">Bienvenido de vuelta</h3>

        <p class="mt-1 text-center text-gray-500 dark:text-gray-400">Iniciar sesion o crear cuenta</p>

        <form method="POST" action="auth">
            <div class="w-full mt-4">
                <input class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 focus:border-blue-400 dark:focus:border-blue-300 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300" type="email" id="email" name="email" placeholder="Email" required />
            </div>

            <div class="w-full mt-4">
                <input class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 focus:border-blue-400 dark:focus:border-blue-300 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300" type="password" id="password" name="password" placeholder="Contraseña" required />
            </div>

            <div class="flex items-center justify-between mt-4">
                <a href="#" class="text-sm text-gray-600 dark:text-gray-200 hover:text-gray-500">Olvidaste la Contraseña?</a>

                 <?php if ($message != null): ?>
            <div class="alert alert-warning" role="alert">
                <?= $message ?>
            </div>
        <?php endif ?>
                <button class="px-6 py-2 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-500 rounded-lg hover:bg-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-50">
                    Iniciar sesion
                </button>
            </div>
        </form>
    </div>

    <div class="flex items-center justify-center py-4 text-center bg-gray-50 dark:bg-gray-700">
        <span class="text-sm text-gray-600 dark:text-gray-200">No tienes cuenta? </span>

        <a href="register" class="mx-2 text-sm font-bold text-blue-500 dark:text-blue-400 hover:underline">Registrarte</a>
    </div>
</div>

<?php require './template/footer.phtml' ?>
